# Generated by Django 2.0.4 on 2018-04-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muafiyetogr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogrenci',
            name='ogr_number',
            field=models.IntegerField(unique=True),
        ),
    ]
