# Generated by Django 2.0.4 on 2018-04-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muafiyetogr', '0003_ogrenci_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Okul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okul_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='ogrenci',
            old_name='email',
            new_name='ogr_email',
        ),
        migrations.RenameField(
            model_name='ogrenci',
            old_name='name',
            new_name='ogr_name',
        ),
        migrations.RenameField(
            model_name='ogrenci',
            old_name='okul',
            new_name='ogr_okul',
        ),
        migrations.RenameField(
            model_name='ogrenci',
            old_name='surname',
            new_name='ogr_surname',
        ),
    ]
