# Generated by Django 2.0.4 on 2018-04-28 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muafiyetogr', '0004_auto_20180422_2020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ogrenci',
        ),
    ]
