# Generated by Django 2.0.4 on 2018-04-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muafiyetogr', '0005_delete_ogrenci'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ogrenci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogr_name', models.CharField(max_length=50)),
                ('ogr_surname', models.CharField(max_length=50)),
                ('ogr_okul', models.CharField(choices=[('atatürk üniversitesi', 'atatürk üniversitesi'), ('istanbul üniversitesi', 'istanbul üniversitesi'), ('ankara üniversitesi', 'ankara üniversitesi'), ('antalya üniversitesi', 'antalya üniversitesi')], max_length=100)),
                ('ogr_bolum', models.CharField(max_length=100)),
                ('ogr_number', models.CharField(max_length=9, unique=True)),
                ('ogr_email', models.EmailField(max_length=100, unique=True)),
                ('ogr_password', models.CharField(max_length=50)),
                ('ogr_telefon', models.CharField(max_length=15)),
                ('ogr_photo', models.FileField(upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
