# Generated by Django 2.0.4 on 2018-04-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muafiyetogr', '0006_ogrenci'),
    ]

    operations = [
        migrations.CreateModel(
            name='bolumler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolum_adi', models.CharField(max_length=50)),
                ('fakulte_adi', models.CharField(max_length=50)),
            ],
        ),
    ]
