# Generated by Django 2.0.4 on 2018-04-28 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muafiyetogr', '0007_bolumler'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bolumler',
            old_name='bolum_adi',
            new_name='bolum_name',
        ),
        migrations.RenameField(
            model_name='bolumler',
            old_name='fakulte_adi',
            new_name='fakulte_name',
        ),
    ]
