# Generated by Django 2.0.4 on 2018-04-28 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muafiyetogr', '0008_auto_20180428_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ders_kodu', models.CharField(max_length=8)),
                ('ders_name', models.CharField(max_length=50)),
                ('kredi_sayisi', models.IntegerField()),
                ('icerik', models.CharField(max_length=500)),
                ('bolum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muafiyetogr.bolumler')),
            ],
        ),
    ]
