# Generated by Django 2.0.4 on 2018-04-28 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muafiyetogr', '0009_ders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ogretimuyesi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogretim_uyesi_name', models.CharField(max_length=50)),
                ('ogretim_uyesi_surname', models.CharField(max_length=50)),
                ('unvan', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ogretim_uyesi_telefon', models.CharField(max_length=15)),
                ('ogretim_uyesi_password', models.CharField(max_length=50)),
                ('bolum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muafiyetogr.bolumler')),
            ],
        ),
    ]
