# Generated by Django 2.0.4 on 2018-04-28 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muafiyetogr', '0010_ogretimuyesi'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnayFormu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ders1', models.CharField(max_length=75)),
                ('kredi_sayisi1', models.IntegerField()),
                ('harf_notu1', models.CharField(choices=[('AA', 'AA'), ('BA', 'BA'), ('BB', 'BB'), ('CB', 'CB'), ('CC', 'CC'), ('DC', 'DC'), ('DD', 'DD'), ('FF', 'FF')], max_length=2)),
                ('OnayDurumu', models.CharField(choices=[('onay', 'onay'), ('Red', 'Red'), ('bekleniyor', 'bekleniyor')], max_length=6)),
                ('harf_notu2', models.CharField(choices=[('AA', 'AA'), ('BA', 'BA'), ('BB', 'BB'), ('CB', 'CB'), ('CC', 'CC'), ('DC', 'DC'), ('DD', 'DD'), ('FF', 'FF')], max_length=2)),
                ('ders2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muafiyetogr.Ders')),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muafiyetogr.Ogrenci')),
                ('ogretim_uyesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muafiyetogr.Ogretimuyesi')),
            ],
        ),
    ]
