# Generated by Django 2.0.4 on 2018-04-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muafiyetogr', '0012_auto_20180428_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onayformu',
            name='harf_notu1',
            field=models.CharField(choices=[('AA', 'AA'), ('BA', 'BA'), ('BB', 'BB'), ('CB', 'CB'), ('CC', 'CC'), ('DC', 'DC'), ('DD', 'DD'), ('FF', 'FF'), ('---', '---')], max_length=2),
        ),
        migrations.AlterField(
            model_name='onayformu',
            name='harf_notu2',
            field=models.CharField(choices=[('AA', 'AA'), ('BA', 'BA'), ('BB', 'BB'), ('CB', 'CB'), ('CC', 'CC'), ('DC', 'DC'), ('DD', 'DD'), ('FF', 'FF'), ('---', '---')], default='---', max_length=2),
        ),
    ]
